#!/usr/bin/env python3
"""Generate guide/verification-links-<date>.md — one line per hotel record.

Every hotel gets a line listing, for each captured stay window, the exact
Booking.com dated page (primary verified source) and the Agoda property page
(secondary verified source), each LINK LABELLED WITH ITS SITE. A record with
no Agoda listing prints the recorded not-found finding instead of a blank.

Run:  python3 tools/build_link_checklist.py [YYYY-MM-DD]
"""
import datetime as _dt
import json
import sys

HOTELS = "data/hotels.json"
OUT_TMPL = "guide/verification-links-{date}.md"

RATE_FIELDS = [
    ("refundableRate", None),
    ("refundableRateNov9", "Nov 9–15"),
    ("refundableRateNov15", "Nov 15–22"),
]
WINDOWS = {
    "refundableRate": "the record's stored window",
    "refundableRateNov9": "Nov 9–15, 2026 (6 nights)",
    "refundableRateNov15": "Nov 15–22, 2026 (7 nights)",
}


def base(url):
    return (url or "").split("?")[0]


def row(h):
    hid = h["id"]
    name = h["name"]
    city = h["city"]
    cells = [f"**{name}**", city, f"`{hid}`"]
    flags = []
    for field, label in RATE_FIELDS:
        r = h.get(field)
        if not isinstance(r, dict):
            continue
        window = label or f"{r.get('stayCheckIn')}–{r.get('stayCheckOut')}"
        url = r.get("sourceUrl") or ""
        if url:
            state = "priced" if r.get("available") and r.get("pricePerNight") else "no-rate"
            captured = str(r.get("capturedAtUtc", ""))[:10]
            cells.append(
                f"[Booking.com {window}]({url}) — {state}, captured {captured}"
            )
        else:
            cells.append(f"Booking.com {window} — no source URL on row")
            flags.append(f"no-booking-url-{window}")
    if len(cells) == 3:  # no rate block at all (new-round records): still give the reviewer a Booking link
        v = h.get("verification") or {}
        bu = next((u for u in (v.get("sourceUrl"), h.get("compareUrl")) if u and "booking.com" in str(u)), None)
        ds = h.get("distributionStatus") or {}
        dstext = (ds.get("status") if isinstance(ds, dict) else str(ds)) or "no dated capture in this round"
        if bu:
            cells.append(f"[Booking.com property page (index copy)]({bu}) — no dated capture 2026-08-30; {dstext}")
            flags.append("pending-dated-capture")
        else:
            cells.append(f"Booking.com — no listing found in the 2026-08-30 index round; {dstext}")
            flags.append("no-booking-page")
    s = h.get("secondarySource") or {}
    if s.get("status") == "verified" and s.get("url"):
        checked = str(s.get("lastCheckedUtc", ""))[:10]
        method = "page fetched" if s.get("checkMethod") == "property-page-fetched" else "search index"
        page_kind = "property page" if s.get("linkType") == "property-page" else "reviews page"
        cells.append(f"[Agoda {page_kind}]({s['url']}) — {method}, checked {checked}")
        if s.get("linkType") == "reviews-page":
            flags.append("agoda-reviews-route")
    elif s.get("status") == "not-found":
        cells.append(f"Agoda — no listing matching this exact identity ({str(s.get('lastCheckedUtc',''))[:10]}): {s.get('note','')[:120]}")
    elif s.get("status") == "unresolved":
        cells.append(f"⚠️ Agoda — listing known to exist, URL unresolved ({str(s.get('lastCheckedUtc',''))[:10]}): look it up manually on agoda.com. {s.get('note','')[:140]}")
        flags.append("agoda-unresolved-manual-lookup")
    else:
        cells.append("⚠️ Agoda — **not yet checked**")
        flags.append("agoda-unchecked")
    if h.get("distributionStatus") and "Not distributed" in str(h.get("distributionStatus")):
        flags.append("not-on-Booking")
    cells.append("⚑ " + ", ".join(flags) if flags else "—")
    return "| " + " | ".join(cells) + " |"


def main():
    date = sys.argv[1] if len(sys.argv) > 1 else _dt.date.today().isoformat()
    data = json.load(open(HOTELS, encoding="utf-8"))
    hotels = data["hotels"]
    cities = []
    for h in hotels:
        if h["city"] not in cities:
            cities.append(h["city"])

    lines = [
        f"# Link-by-link verification sheet — {date}",
        "",
        "Generated by `tools/build_link_checklist.py` from `data/hotels.json`; do not hand-edit.",
        "**Every link names the site it opens.** Primary verified source = **Booking.com** dated rate page.",
        "Secondary verified source = **Agoda** — labeled as either an Agoda **property page** (canonical `/hotel/`)",
        "or an Agoda **reviews page** (`/reviews/`; flagged `⚑ agoda-reviews-route`). A record without an Agoda",
        "link carries either an explicit not-found finding or an 'unresolved' flag (listing known, URL not",
        "surfaced by the index — look it up manually). A blank is always a recorded result, never an omission.",
        "The 12 records previously pointing at Agoda guide/city/maps pages, and their replacement property pages,",
        "are documented in `guide/verification-agoda-property-page-hardening-2026-09-08.md`.",
        "",
        "Manual review recipe for one line:",
        "",
        "1. Open the **Booking.com** link — check the URL's `checkin`/`checkout` match the window label,",
        "   then read the room name, bed line, cancellation sentence and price on that exact row.",
        "2. Open the **Agoda** link — confirm the property name and address, and that it is the same",
        "   building (compare street address / coordinates, not just the brand name).",
        "3. Anything that disagrees with the data is a flag: record it, do not silently overwrite it.",
        "",
        f"Records covered: **{len(hotels)}**. Captured windows: Nov 1–9 (8 nt, Seoul/Suwon/alternates), Nov 9–15 (6 nt, Busan focus + Gyeongju), Nov 15–22 (7 nt, Busan + Seoul alternates).",
        "",
    ]
    counts = {"verified": 0, "not-found": 0, "unresolved": 0, "unchecked": 0}
    for city in cities:
        subset = [h for h in hotels if h["city"] == city]
        lines.append(f"\n## {city} — {len(subset)} records\n")
        lines.append("| Hotel | City | id | Booking.com (primary) captures | Agoda (secondary) | Flags |")
        lines.append("|---|---|---|---|---|---|")
        for h in sorted(subset, key=lambda x: x["name"].lower()):
            s = h.get("secondarySource") or {}
            if s.get("status") == "verified":
                counts["verified"] += 1
            elif s.get("status") == "not-found":
                counts["not-found"] += 1
            elif s.get("status") == "unresolved":
                counts["unresolved"] += 1
            else:
                counts["unchecked"] += 1
            lines.append(row(h))
    property_pages = reviews_pages = 0
    for h in hotels:
        s = h.get("secondarySource") or {}
        if s.get("status") == "verified" and s.get("url"):
            if s.get("linkType") == "property-page":
                property_pages += 1
            elif s.get("linkType") == "reviews-page":
                reviews_pages += 1
    lines += [
        "",
        "## Coverage summary",
        "",
        f"- Agoda links verified: **{counts['verified']}**",
        f"- Agoda canonical property pages (`/hotel/`): **{property_pages}**",
        f"- Agoda property reviews pages (`/reviews/`, carry the ⚑ agoda-reviews-route flag): **{reviews_pages}**",
        f"- Agoda explicit not-found findings: **{counts['not-found']}**",
        f"- Agoda listings known but URL unresolved (manual lookup needed): **{counts['unresolved']}**",
        f"- Agoda check still outstanding (queue): **{counts['unchecked']}**",
        f"- Records total: **{len(hotels)}**",
        "",
    ]
    out = OUT_TMPL.format(date=date)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out}: {len(hotels)} lines; agoda verified={counts['verified']} not-found={counts['not-found']} unchecked={counts['unchecked']}")


if __name__ == "__main__":
    main()
